services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=janus_dev
  
  airflow-webserver:
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__WEBSERVER__DEBUG=True
  
  streamlit:
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_ENV=development
      - STREAMLIT_DEBUG=true